const lawyers = [
  {
    id: 1,
    name: "Adv. K.G. Raghavan",
    specialization: "Criminal",
    experience: "40+ Years",
    location: "Bengaluru",
    fee: 3500,
    rating: 5.0,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about:
  "Senior criminal advocate with over 40 years of experience handling high-profile criminal and constitutional matters.",
availability: "Available Today",
image: "https://via.placeholder.com/200",
  },
  {
    id: 2,
    name: "Adv. C.V. Nagesh",
    specialization: "Criminal",
    experience: "30+ Years",
    location: "Bengaluru",
    fee: 3000,
    rating: 4.9,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 3,
    name: "Adv. Udaya Holla",
    specialization: "Corporate",
    experience: "35+ Years",
    location: "Bengaluru",
    fee: 3200,
    rating: 4.9,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 4,
    name: "Adv. Sajan Poovayya",
    specialization: "Corporate",
    experience: "25+ Years",
    location: "Bengaluru",
    fee: 3000,
    rating: 4.8,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 5,
    name: "Adv. Dhyan Chinnappa",
    specialization: "Civil",
    experience: "25+ Years",
    location: "Bengaluru",
    fee: 2500,
    rating: 4.8,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 6,
    name: "Adv. Ashok Haranahalli",
    specialization: "Civil",
    experience: "35+ Years",
    location: "Bengaluru",
    fee: 3200,
    rating: 4.9,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 7,
    name: "Adv. M.B. Nargund",
    specialization: "Property",
    experience: "28+ Years",
    location: "Bengaluru",
    fee: 2800,
    rating: 4.8,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 8,
    name: "Adv. V. Lakshminarayana",
    specialization: "Cyber",
    experience: "20+ Years",
    location: "Bengaluru",
    fee: 3000,
    rating: 4.8,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 9,
    name: "Adv. Kiran S. Javali",
    specialization: "Family",
    experience: "18+ Years",
    location: "Bengaluru",
    fee: 2200,
    rating: 4.7,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 10,
    name: "Adv. Nandini Gowda",
    specialization: "Family",
    experience: "15+ Years",
    location: "Bengaluru",
    fee: 2000,
    rating: 4.7,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 11,
    name: "Adv. Ravi Prakash",
    specialization: "Labour",
    experience: "20+ Years",
    location: "Bengaluru",
    fee: 2400,
    rating: 4.6,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
  {
    id: 12,
    name: "Adv. Meera Rao",
    specialization: "Consumer",
    experience: "17+ Years",
    location: "Bengaluru",
    fee: 2100,
    rating: 4.7,
    languages: ["Kannada", "English", "Hindi"],
court: "High Court of Karnataka",
education: "LL.B, National Law School of India University",
about: "Experienced advocate specializing in criminal and constitutional matters.",
availability: "Available Today",
image: "https://placehold.co/250x250?text=Lawyer",
  },
];

export default lawyers;